package Pojo;
// Generated 01.Oca.2019 16:33:35 by Hibernate Tools 4.3.1



/**
 * Adminler generated by hbm2java
 */
public class Adminler  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

    public Adminler() {
    }

    public Adminler(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


