package Pojo;
// Generated 01.Oca.2019 16:33:35 by Hibernate Tools 4.3.1

/**
 * Calisanlar generated by hbm2java
 */
public class Calisanlar implements java.io.Serializable {

    private Integer id;
    private String ad;
    private String soyad;
    private String departman;
    private String maas;

    public Calisanlar() {

    }

    public Calisanlar(String ad, String soyad, String departman, String maas) {
        this.ad = ad;
        this.soyad = soyad;
        this.departman = departman;
        this.maas = maas;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAd() {
        return this.ad;
    }

    public void setAd(String ad) {
        this.ad = ad;
    }

    public String getSoyad() {
        return this.soyad;
    }

    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }

    public String getDepartman() {
        return this.departman;
    }

    public void setDepartman(String departman) {
        this.departman = departman;
    }

    public String getMaas() {
        return this.maas;
    }

    public void setMaas(String maas) {
        this.maas = maas;
    }

}
